on:
  push:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - run: pip install bcedd
      - run: python -m bcedd -c jp kr en tw -o .

      - uses: stefanzweifel/git-auto-commit-action@v7
        # with:
        #   commit_message: "update: event data"
